lines:
  - line_ref: "STIF:Line::C01376:"
    line_label: "metro_6"
    target_stop_refs:
      - "STIF:StopPoint:Q:463103:"
      - "STIF:StopPoint:Q:463128:"
    enabled: true

  - line_ref: "STIF:Line::C01377:"
    line_label: "metro_7"
    target_stop_refs:
      - "STIF:StopPoint:Q:22381:"
      - "STIF:StopPoint:Q:463026:"
      - "STIF:StopPoint:Q:463155:"
    enabled: true