idfm:
  api_key_file: "secrets/idfm_api_key.txt"
  base_url: "https://prim.iledefrance-mobilites.fr/marketplace/stop-monitoring"
  line_request_base_url: "https://prim.iledefrance-mobilites.fr/marketplace/requete-ligne"
  timeout_seconds: 20
  poll_interval_seconds: 60